import React from "react"


const Style={

    bgGray:{
        background:"#444"
    },
    bgDarkGray:{
        background:"#111"
    },
    fullSize:{
        width:"100%",
        height:"100vh"
    },
    w100:{
        width:"100%"
    },
    h90:{
        height:"60%"
    },
    pTB3:{
        paddingTop:15,
        paddingBottom:15
    },
    p10:{
        padding:40
    },
    textWhite:{
        color:"#fff"
    },
    fontBig:{
        fontSize:30
    },
    noDecoration:{
        textDecoration:"none"
    },
    bgRed:{
        background:"#f00"
    },
    bgLightGray:{
        background:"#222"
    },
    center:{
        display:"flex",
        justifyContent:"center",
        alignItems:"center"
    },
    flexRow:{
        flexDirection:"column"
    },
    inputField:{
        padding:10,
        borderRadius:6,
        border:"none"
    },
    displayBlock:{
        display:"block"
    },
    mt20:{
        marginTop:20
    }, 
    submitButton:{
        background:"#5bc0de",
        padding:10,
        borderRadius:10,
        border:"none"
    }, 
    footer:{
        position:"fixed",
        left:0,
        right:0,
        width:"100%"
    },
    dFlex:{
        display:"flex"
    },
    justifyContentEvenly:{
        justifyContent:"space-evenly"
    },
    dNone:{
        display:"none"
    }

}
export default Style